{% set name = "bash-completion" %}
{% set version = "2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scop/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 16adefabf43ec8ffb473704f5724d775c2f47e9f750d7d608f0251ec21fe8813
  patches:
    # add a conda specific library loaded flag
    - track-conda-loaded.patch

    # search for completions in the conda environment
    - completions-path.patch

    # adjust double load trap to use conda specific
    - double-load-trap.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake

test:
  source_files:
    - bash_completion

  requires:
    - bash >=4.1

about:
  home: https://github.com/scop/bash-completion
  license: GPL-2.0-only
  license_file: COPYING
  summary: Programmable completion functions for bash.

extra:
  recipe-maintainers:
    - tartansandal
