{% set version = "2.16.0" %}

package:
  name: bash-completion
  version: {{ version }}

source:
  url: https://github.com/scop/bash-completion/archive/{{ version }}.tar.gz
  sha256: c4d7edf0b035d8f6ed33294380326bde1fb8a4a8e24699566d545b4276141cc2
  patches:
    # add a conda specific library loaded flag
    - 0001-Track-Conda-Loaded.patch

    # search for completions in the conda environment
    - 0002-Add-to-completitions-path.patch

    # adjust double load trap to use conda specific
    - 0003-Double-load-trap.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - make

test:
  source_files:
    - bash_completion
  requires:
    - bash >=4.1
  commands:
    # Ensure the library loads without error at least
    - bash -e bash_completion

about:
  home: https://github.com/scop/bash-completion
  license: GPL-2.0-only
  license_file: COPYING
  summary: Programmable completion functions for bash.

extra:
  recipe-maintainers:
    - tartansandal
    - matthiasdiener
    - hmaarrfk
