{% set name = "bash-completion" %}
{% set version = "2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scop/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 185f5c912440cc99c066315047dcced7e314ded24cf08732125bd24ad928d29f
  patches:
    # add a conda specific library loaded flag
    - track-conda-loaded.patch

    # search for completions in the conda environment
    - completions-path.patch

    # adjust double load trap to use conda specific
    - double-load-trap.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - autoconf
    - automake

test:
  source_files:
    - bash_completion

  requires:
    - bash >=4.1

about:
  home: https://github.com/scop/bash-completion
  license: GPL2
  license_file: COPYING
  summary: "Programmable completion functions for bash."

extra:
  recipe-maintainers:
    - tartansandal
